### ISSUE TITLE
Verificar a precedência entre o default e cada bacia

### ISSUE THREAD

**Issue by cmotadev** [sgb-cprm/sace-helm#1]
O erro foi detectado na obtenção do item imageDir, que não está sendo reconhecido em default.

Comportamento esperado

``` yaml
config:
  default:
    enableScheduling: false
    enableRetrieve: false
    imageDir: /mnt/sace/data
    jvm:
      xmx: 3096
      xms: 2098
basins:
    - name: araguaia
      title: Bacia do Araguaia
      # ...
```

Possível solução: usar a função [merge](https://helm.sh/docs/chart_template_guide/function_list/#merge-mustmerge) para gerenciar as listas de objetos default e basins
